/**
 * IB Biology syllabus specification for the Biology IA Idea Generator.
 * Used by biologyIdeaGenerator.js to build BIOLOGY_IDEA_CONFIG_JSON.
 */

export const BIOLOGY_SYLLABUS_SPEC = {
  'A1.1': {
    title: 'Water',
    SL_HL: {
      'A1.1.1': 'Water as the medium for life',
      'A1.1.2': 'Hydrogen bonds as a consequence of the polar covalent bonds within water molecules',
      'A1.1.3': 'Cohesion of water molecules due to hydrogen bonding and consequences for organisms',
      'A1.1.4': 'Adhesion of water to materials that are polar or charged and impacts for organisms',
      'A1.1.5': 'Solvent properties of water linked to its role as a medium for metabolism and for transport in plants and animals',
      'A1.1.6': 'Physical properties of water and the consequences for animals in aquatic habitats',
    },
    HL_only: {
      'A1.1.7': 'Extraplanetary origin of water on Earth and reasons for its retention',
      'A1.1.8': 'Relationship between the search for extraterrestrial life and the presence of water',
    },
  },
  'A1.2': {
    title: 'Nucleic acids',
    SL_HL: {
      'A1.2.1': 'DNA as the genetic material of all living organisms',
      'A1.2.2': 'Components of a nucleotide',
      'A1.2.3': 'Sugar–phosphate bonding and the sugar–phosphate backbone of DNA and RNA',
      'A1.2.4': 'Bases in each nucleic acid that form the basis of a code',
      'A1.2.5': 'RNA as a polymer formed by condensation of nucleotide monomers',
      'A1.2.6': 'DNA as a double helix made of two antiparallel strands linked by complementary base pairing',
      'A1.2.7': 'Differences between DNA and RNA',
      'A1.2.8': 'Role of complementary base pairing in allowing genetic information to be replicated and expressed',
      'A1.2.9': 'Diversity of possible DNA base sequences and the limitless capacity of DNA for storing information',
      'A1.2.10': 'Conservation of the genetic code across all life forms as evidence of universal common ancestry',
    },
    HL_only: {
      'A1.2.11': 'Directionality of RNA and DNA',
      'A1.2.12': 'Purine-to-pyrimidine bonding as a component of DNA helix stability',
      'A1.2.13': 'Structure of a nucleosome',
      'A1.2.14': 'Evidence from the Hershey–Chase experiment for DNA as the genetic material',
      'A1.2.15': "Chargaff's data on the relative amounts of pyrimidine and purine bases across diverse life forms",
    },
  },
  'A2.1': {
    title: 'Origins of cells',
    HL_only: {
      'A2.1.1': 'Conditions on early Earth and the pre-biotic formation of carbon compounds',
      'A2.1.2': 'Cells as the smallest units of self-sustaining life',
      'A2.1.3': 'Challenge of explaining the spontaneous origin of cells',
      'A2.1.4': 'Evidence for the origin of carbon compounds',
      'A2.1.5': 'Spontaneous formation of vesicles by coalescence of fatty acids into spherical bilayers',
      'A2.1.6': 'RNA as a presumed first genetic material',
      'A2.1.7': 'Evidence for a last universal common ancestor',
      'A2.1.8': 'Approaches used to estimate dates of the first living cells and the last universal common ancestor',
      'A2.1.9': 'Evidence for the evolution of the last universal common ancestor in the vicinity of hydrothermal vents',
    },
  },
  'A2.2': {
    title: 'Cell structure',
    SL_HL: {
      'A2.2.1': 'Cells as the basic structural unit of all living organisms',
      'A2.2.2': 'Microscopy skills',
      'A2.2.3': 'Developments in microscopy',
      'A2.2.4': 'Structures common to cells in all living organisms',
      'A2.2.5': 'Prokaryote cell structure',
      'A2.2.6': 'Eukaryote cell structure',
      'A2.2.7': 'Processes of life in unicellular organisms',
      'A2.2.8': 'Differences in eukaryotic cell structure between animals, fungi and plants',
      'A2.2.9': 'Atypical cell structure in eukaryotes',
      'A2.2.10': 'Cell types and cell structures viewed in light and electron micrographs',
      'A2.2.11': 'Drawing and annotation based on electron micrographs',
    },
    HL_only: {
      'A2.2.12': 'Origin of eukaryotic cells by endosymbiosis',
      'A2.2.13': 'Cell differentiation as the process for developing specialized tissues in multicellular organisms',
      'A2.2.14': 'Evolution of multicellularity',
    },
  },
  'A2.3': {
    title: 'Viruses',
    HL_only: {
      'A2.3.1': 'Structural features common to viruses',
      'A2.3.2': 'Diversity of structure in viruses',
      'A2.3.3': 'Lytic cycle of a virus',
      'A2.3.4': 'Lysogenic cycle of a virus',
      'A2.3.5': 'Evidence for several origins of viruses from other organisms',
      'A2.3.6': 'Rapid evolution in viruses',
    },
  },
  'A3.1': {
    title: 'Diversity of organisms',
    SL_HL: {
      'A3.1.1': 'Variation between organisms as a defining feature of life',
      'A3.1.2': 'Species as groups of organisms with shared traits',
      'A3.1.3': 'Binomial system for naming organisms',
      'A3.1.4': 'Biological species concept',
      'A3.1.5': 'Difficulties distinguishing between populations and species during speciation',
      'A3.1.6': 'Diversity in chromosome numbers of plant and animal species',
      'A3.1.7': 'Karyotyping and karyograms',
      'A3.1.8': 'Unity and diversity of genomes within species',
      'A3.1.9': 'Diversity of eukaryote genomes',
      'A3.1.10': 'Comparison of genome sizes',
      'A3.1.11': 'Current and potential future uses of whole genome sequencing',
    },
    HL_only: {
      'A3.1.12': 'Difficulties applying the biological species concept to asexually reproducing species',
      'A3.1.13': 'Chromosome number as a shared trait within a species',
      'A3.1.14': 'Engagement with local species to develop a dichotomous key',
      'A3.1.15': 'Identification of species from environmental DNA using barcodes',
    },
  },
  'A3.2': {
    title: 'Classification and cladistics',
    HL_only: {
      'A3.2.1': 'Need for classification of organisms',
      'A3.2.2': 'Difficulties classifying organisms into the traditional hierarchy of taxa',
      'A3.2.3': 'Advantages of classification corresponding to evolutionary relationships',
      'A3.2.4': 'Clades as groups of organisms with common ancestry',
      'A3.2.5': 'Gradual accumulation of sequence differences as the basis for molecular clocks',
      'A3.2.6': 'Base sequences as the basis for constructing cladograms',
      'A3.2.7': 'Analysing cladograms',
      'A3.2.8': 'Using cladistics to evaluate classifications',
      'A3.2.9': 'Classification of organisms into three domains using rRNA sequences',
    },
  },
  'A4.1': {
    title: 'Evolution and speciation',
    SL_HL: {
      'A4.1.1': 'Evolution as change in heritable characteristics of a population',
      'A4.1.2': 'Evidence for evolution from base sequences',
      'A4.1.3': 'Evidence for evolution from selective breeding',
      'A4.1.4': 'Evidence for evolution from homologous structures',
      'A4.1.5': 'Convergent evolution as the origin of analogous structures',
      'A4.1.6': 'Speciation by splitting of pre-existing species',
      'A4.1.7': 'Roles of reproductive isolation and differential selection in speciation',
    },
    HL_only: {
      'A4.1.8': 'Differences between sympatric and allopatric speciation',
      'A4.1.9': 'Adaptive radiation as a source of biodiversity',
      'A4.1.10': 'Barriers to hybridization and sterility of hybrids',
      'A4.1.11': 'Abrupt speciation in plants by hybridization and polyploidy',
    },
  },
  'A4.2': {
    title: 'Conservation of biodiversity',
    SL_HL: {
      'A4.2.1': 'Biodiversity as the variety of life in all its forms',
      'A4.2.2': 'Comparisons between current and past biodiversity levels',
      'A4.2.3': 'Causes of anthropogenic species extinction',
      'A4.2.4': 'Causes of ecosystem loss',
      'A4.2.5': 'Evidence for a biodiversity crisis',
      'A4.2.6': 'Causes of the current biodiversity crisis',
      'A4.2.7': 'Need for several approaches to conservation',
      'A4.2.8': 'Selection of evolutionarily distinct and globally endangered species',
    },
  },
  'B1.1': {
    title: 'Carbohydrates and lipids',
    SL_HL: {
      'B1.1.1': 'Chemical properties of carbon allowing diverse compounds',
      'B1.1.2': 'Production of macromolecules by condensation reactions',
      'B1.1.3': 'Digestion of polymers by hydrolysis',
      'B1.1.4': 'Form and function of monosaccharides',
      'B1.1.5': 'Polysaccharides as energy storage compounds',
      'B1.1.6': 'Structure of cellulose related to its function',
      'B1.1.7': 'Role of glycoproteins in cell–cell recognition',
      'B1.1.8': 'Hydrophobic properties of lipids',
      'B1.1.9': 'Formation of triglycerides and phospholipids',
      'B1.1.10': 'Difference between saturated and unsaturated fatty acids',
      'B1.1.11': 'Triglycerides in adipose tissue for energy storage',
      'B1.1.12': 'Formation of phospholipid bilayers',
      'B1.1.13': 'Ability of non-polar steroids to pass through membranes',
    },
  },
  'B1.2': {
    title: 'Proteins',
    SL_HL: {
      'B1.2.1': 'Generalized structure of an amino acid',
      'B1.2.2': 'Condensation reactions forming peptides',
      'B1.2.3': 'Dietary requirements for amino acids',
      'B1.2.4': 'Infinite variety of possible peptide chains',
      'B1.2.5': 'Effect of pH and temperature on protein structure',
    },
    HL_only: {
      'B1.2.6': 'Chemical diversity in R-groups',
      'B1.2.7': 'Impact of primary structure on protein conformation',
      'B1.2.8': 'Secondary structure of proteins',
      'B1.2.9': 'Dependence of tertiary structure on bonding',
      'B1.2.10': 'Effect of polar and non-polar amino acids on tertiary structure',
      'B1.2.11': 'Quaternary structure of proteins',
      'B1.2.12': 'Relationship of form and function in globular and fibrous proteins',
    },
  },
  'B2.1': {
    title: 'Membranes and membrane transport',
    SL_HL: {
      'B2.1.1': 'Lipid bilayers as the basis of cell membranes',
      'B2.1.2': 'Lipid bilayers as barriers',
      'B2.1.3': 'Simple diffusion across membranes',
      'B2.1.4': 'Integral and peripheral proteins in membranes',
      'B2.1.5': 'Movement of water by osmosis',
      'B2.1.6': 'Channel proteins for facilitated diffusion',
      'B2.1.7': 'Pump proteins for active transport',
      'B2.1.8': 'Selectivity in membrane permeability',
      'B2.1.9': 'Structure and function of glycoproteins and glycolipids',
      'B2.1.10': 'Fluid mosaic model of membrane structure',
    },
    HL_only: {
      'B2.1.11': 'Fatty acid composition and membrane fluidity',
      'B2.1.12': 'Cholesterol and membrane fluidity',
      'B2.1.13': 'Membrane fluidity and vesicle formation',
      'B2.1.14': 'Gated ion channels in neurons',
      'B2.1.15': 'Sodium–potassium pumps',
      'B2.1.16': 'Sodium-dependent glucose cotransporters',
      'B2.1.17': 'Adhesion of cells to form tissues',
    },
  },
  'B2.2': {
    title: 'Organelles and compartmentalization',
    SL_HL: {
      'B2.2.1': 'Organelles as discrete functional subunits',
      'B2.2.2': 'Separation of nucleus and cytoplasm',
      'B2.2.3': 'Advantages of compartmentalization',
    },
    HL_only: {
      'B2.2.4': 'Adaptations of mitochondria',
      'B2.2.5': 'Adaptations of chloroplasts',
      'B2.2.6': 'Functional benefits of the nuclear membrane',
      'B2.2.7': 'Structure and function of ribosomes and rough ER',
      'B2.2.8': 'Structure and function of the Golgi apparatus',
      'B2.2.9': 'Structure and function of vesicles',
    },
  },
  'B2.3': {
    title: 'Cell specialization',
    SL_HL: {
      'B2.3.1': 'Production and differentiation of unspecialized cells',
      'B2.3.2': 'Properties of stem cells',
      'B2.3.3': 'Stem cell niches in adult humans',
      'B2.3.4': 'Differences between totipotent, pluripotent and multipotent cells',
      'B2.3.5': 'Cell size as an aspect of specialization',
      'B2.3.6': 'Surface area-to-volume ratios and constraints on cell size',
    },
    HL_only: {
      'B2.3.7': 'Adaptations to increase surface area-to-volume ratios',
      'B2.3.8': 'Adaptations of type I and type II pneumocytes',
      'B2.3.9': 'Adaptations of cardiac and skeletal muscle cells',
      'B2.3.10': 'Adaptations of sperm and egg cells',
    },
  },
  'B3.1': {
    title: 'Gas exchange',
    SL_HL: {
      'B3.1.1': 'Gas exchange as a vital function',
      'B3.1.2': 'Properties of gas-exchange surfaces',
      'B3.1.3': 'Maintenance of concentration gradients',
      'B3.1.4': 'Adaptations of mammalian lungs',
      'B3.1.5': 'Ventilation of the lungs',
      'B3.1.6': 'Measurement of lung volumes',
      'B3.1.7': 'Adaptations for gas exchange in leaves',
      'B3.1.8': 'Distribution of tissues in a leaf',
      'B3.1.9': 'Transpiration as a consequence of gas exchange',
      'B3.1.10': 'Stomatal density',
    },
    HL_only: {
      'B3.1.11': 'Adaptations of foetal and adult haemoglobin',
      'B3.1.12': 'Bohr shift',
      'B3.1.13': 'Oxygen dissociation curves',
    },
  },
  'B3.2': {
    title: 'Transport',
    SL_HL: {
      'B3.2.1': 'Adaptations of capillaries',
      'B3.2.2': 'Structure of arteries and veins',
      'B3.2.3': 'Adaptations of arteries',
      'B3.2.4': 'Measurement of pulse rates',
      'B3.2.5': 'Adaptations of veins',
      'B3.2.6': 'Causes and consequences of coronary artery occlusion',
      'B3.2.7': 'Transport of water during transpiration',
      'B3.2.8': 'Adaptations of xylem vessels',
      'B3.2.9': 'Distribution of tissues in dicot stems',
      'B3.2.10': 'Distribution of tissues in dicot roots',
    },
    HL_only: {
      'B3.2.11': 'Release and reuptake of tissue fluid',
      'B3.2.12': 'Exchange between tissue fluid and cells',
      'B3.2.13': 'Drainage of tissue fluid into lymph',
      'B3.2.14': 'Single and double circulation',
      'B3.2.15': 'Adaptations of the mammalian heart',
      'B3.2.16': 'Stages in the cardiac cycle',
      'B3.2.17': 'Generation of root pressure',
      'B3.2.18': 'Adaptations of phloem sieve tubes',
    },
  },
  'B3.3': {
    title: 'Muscle and motility',
    HL_only: {
      'B3.3.1': 'Adaptations for movement',
      'B3.3.2': 'Sliding filament model',
      'B3.3.3': 'Role of titin and antagonistic muscles',
      'B3.3.4': 'Structure and function of motor units',
      'B3.3.5': 'Roles of skeletons',
      'B3.3.6': 'Movement at a synovial joint',
      'B3.3.7': 'Range of motion of a joint',
      'B3.3.8': 'Intercostal muscles',
      'B3.3.9': 'Reasons for locomotion',
      'B3.3.10': 'Adaptations for swimming in marine mammals',
    },
  },
  'B4.1': {
    title: 'Adaptation to environment',
    SL_HL: {
      'B4.1.1': 'Habitat as the place in which an organism lives',
      'B4.1.2': 'Adaptations to the abiotic environment',
      'B4.1.3': 'Abiotic variables affecting species distribution',
      'B4.1.4': 'Range of tolerance of a limiting factor',
      'B4.1.5': 'Conditions required for coral reef formation',
      'B4.1.6': 'Abiotic determinants of terrestrial biomes',
      'B4.1.7': 'Biomes as groups of ecosystems',
      'B4.1.8': 'Adaptations to life in hot deserts and tropical rainforest',
    },
  },
  'B4.2': {
    title: 'Ecological niches',
    SL_HL: {
      'B4.2.1': 'Ecological niche as the role of a species',
      'B4.2.2': 'Differences between anaerobes and aerobes',
      'B4.2.3': 'Photosynthesis as a mode of nutrition',
      'B4.2.4': 'Holozoic nutrition in animals',
      'B4.2.5': 'Mixotrophic nutrition in protists',
      'B4.2.6': 'Saprotrophic nutrition',
      'B4.2.7': 'Diversity of nutrition in archaea',
      'B4.2.8': 'Dentition and diet in Hominidae',
      'B4.2.9': 'Adaptations of herbivores and plants',
      'B4.2.10': 'Adaptations of predators and prey',
      'B4.2.11': 'Adaptations of plant form for harvesting light',
      'B4.2.12': 'Fundamental and realized niches',
      'B4.2.13': 'Competitive exclusion and niche uniqueness',
    },
  },
  C1_Interaction_and_Interdependence_Molecules: {
    C1_1_Enzymes_and_metabolism: {
      includes: [
        'Enzymes as biological catalysts increasing reaction rates',
        'Enzyme specificity and control of metabolic pathways',
        'Anabolic vs catabolic reactions with biological examples',
        'Active site structure and globular protein conformation',
        'Induced-fit model and enzyme–substrate interactions',
        'Role of molecular motion and collisions in catalysis',
        'Denaturation effects on enzyme structure and specificity',
        'Effects of temperature, pH, and substrate concentration on enzyme activity',
        'Measurement of enzyme reaction rates',
        'Reduction of activation energy by enzymes',
        'Intracellular vs extracellular enzyme activity (HL)',
        'Heat generation during metabolism (HL)',
        'Linear vs cyclic metabolic pathways (HL)',
        'Allosteric regulation and non-competitive inhibition (HL)',
        'Competitive inhibition and substrate competition (HL)',
        'Feedback inhibition in metabolic pathways (HL)',
        'Mechanism-based irreversible inhibition (HL)',
      ],
    },
    C1_2_Cell_respiration: {
      includes: [
        'ATP structure and role as cellular energy currency',
        'ATP hydrolysis and synthesis',
        'Aerobic vs anaerobic respiration in humans',
        'Rates of cellular respiration and influencing variables',
        'Redox reactions and role of NAD (HL)',
        'Glycolysis pathway overview (HL)',
        'Anaerobic regeneration of NAD (HL)',
        'Link reaction and Krebs cycle (HL)',
        'Electron transport chain and chemiosmosis (HL)',
        'Role of oxygen as terminal electron acceptor',
        'Comparison of lipids vs carbohydrates as respiratory substrates',
      ],
    },
    C1_3_Photosynthesis: {
      includes: [
        'Light energy conversion to chemical energy',
        'Carbon fixation and glucose production',
        'Oxygen production from water photolysis',
        'Chromatographic separation of photosynthetic pigments',
        'Absorption spectra and pigment excitation',
        'Action vs absorption spectra',
        'Limiting factors affecting photosynthesis rate',
        'CO2 enrichment experiments',
        'Photosystems and pigment arrays (HL)',
        'Photolysis, chemiosmosis, and ATP synthesis in thylakoids (HL)',
        'Reduction of NADP and Calvin cycle reactions (HL)',
        'Interdependence of light-dependent and light-independent reactions',
      ],
    },
  },
  C2_Interaction_and_Interdependence_Cells: {
    C2_1_Chemical_signalling_HL_only: {
      includes: [
        'Ligand–receptor specificity',
        'Quorum sensing in bacteria',
        'Hormones, neurotransmitters, cytokines, and Ca2+ signalling',
        'Transmembrane vs intracellular receptors',
        'Signal transduction pathways',
        'G-protein-coupled receptors and second messengers',
        'Tyrosine kinase receptors (insulin)',
        'Steroid hormone receptors and gene expression',
        'Positive and negative feedback in signalling',
      ],
    },
    C2_2_Neural_signalling: {
      includes: [
        'Neuron structure and impulse conduction',
        'Resting potential and ion gradients',
        'Action potential generation and propagation',
        'Factors affecting conduction speed',
        'Chemical synapses and neurotransmitter release',
        'Excitatory and inhibitory postsynaptic potentials',
        'Saltatory conduction in myelinated neurons (HL)',
        'Effects of drugs and toxins on synapses',
        'Pain perception and emergent properties of consciousness',
      ],
    },
  },
  C3_Interaction_and_Interdependence_Organisms: {
    C3_1_Integration_of_body_systems: {
      includes: [
        'Hierarchical organization of body systems',
        'Neural and hormonal integration',
        'Brain and spinal cord coordination',
        'Reflex arcs and involuntary responses',
        'Circadian rhythms and melatonin',
        'Adrenaline responses',
        'Homeostatic feedback of heart rate and ventilation',
        'Plant tropisms and phytohormones (HL)',
        'Auxin transport and phototropism',
        'Positive feedback in fruit ripening',
      ],
    },
    C3_2_Defence_against_disease: {
      includes: [
        'Pathogens and infectious disease',
        'Physical and chemical barriers',
        'Innate vs adaptive immunity',
        'Phagocytosis and lymphocyte activation',
        'Antibody production and memory cells',
        'HIV infection and immune suppression',
        'Antibiotics and resistance',
        'Vaccination and herd immunity',
        'Epidemiological data interpretation (COVID-19)',
      ],
    },
  },
  C4_Interaction_and_Interdependence_Ecosystems: {
    C4_1_Populations_and_communities: {
      includes: [
        'Population definition and sampling methods',
        'Quadrat sampling and capture–recapture',
        'Carrying capacity and density-dependent control',
        'Population growth models',
        'Interspecific interactions',
        'Competition, predation, mutualism, parasitism',
        'Chi-squared tests for species association',
        'Top-down vs bottom-up control',
        'Allelopathy and antibiotic secretion',
      ],
    },
    C4_2_Transfers_of_energy_and_matter: {
      includes: [
        'Energy flow vs matter recycling',
        'Food chains, webs, and trophic levels',
        'Energy pyramids and efficiency losses',
        'Primary and secondary productivity',
        'Carbon cycling and sinks',
        'Keeling curve analysis',
        'Nutrient recycling in ecosystems',
      ],
    },
  },
  D_Continuity_and_Change: {
    D1_Molecular_genetics: {
      includes: [
        'DNA replication mechanisms',
        'PCR and gel electrophoresis',
        'Transcription and translation',
        'Genetic code and mutations',
        'Gene editing and CRISPR (HL)',
        'Epigenetics and gene regulation (HL)',
      ],
    },
    D2_Cell_division_and_expression: {
      includes: [
        'Mitosis and meiosis',
        'Cell cycle control',
        'Cancer and cell division errors',
        'Gene expression regulation',
        'Epigenetic inheritance',
      ],
    },
    D3_Reproduction_and_homeostasis: {
      includes: [
        'Sexual vs asexual reproduction',
        'Hormonal control of reproduction',
        'Inheritance patterns',
        'Homeostatic regulation',
        'Osmoregulation and thermoregulation',
      ],
    },
    D4_Evolution_and_ecosystem_change: {
      includes: [
        'Natural and sexual selection',
        'Hardy–Weinberg equilibrium',
        'Population genetics',
        'Ecosystem stability and tipping points',
        'Climate change impacts',
        'Evolutionary responses to environmental change',
      ],
    },
  },
};
